service: ws-simple-chat

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: ruby2.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::GetAtt: [ ConnectionsTable, Arn ]
  environment:
    TABLE_NAME:
      Ref: ConnectionsTable
  websocketsApiName: ${self:service}
  websocketsApiRouteSelectionExpression: $request.body.message

functions:
  connect:
    handler: app/functions/onconnect.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: app/functions/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  # sendMessage:
  #   handler: app/functions/send_message.handler
  #   events:
  #     - websocket:
  #         path: send_message

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wsSimpleChat_connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
