service: sls-ruby-practice
frameworkVersion: '3'
provider:
  name: aws
  runtime: ruby2.7

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
